### ISSUE TITLE
Not a big issue but s does not serve as default trigger key.

### ISSUE THREAD

**Issue by ubaldot** [girishji/easyjump.vim#2]
Differently on what is written in the README, I had to explicitly set it with the following:

```
g:easyjump_default_keymap = false
nmap s <Plug>EasyjumpJump;
omap s <Plug>EasyjumpJump;
vmap s <Plug>EasyjumpJump;
```
Note that I haven't previously mapped s anywhere else.

**Comment by girishji** [comment]
Should be fixed. please try.

**Comment by ubaldot** [comment]
It works now. Thanks.
