### ISSUE TITLE
Feature request: customizable number of search characters

### ISSUE THREAD

**Issue by jeslinmx** [girishji/easyjump.vim#3]
Hi! Thanks so much for the great plug-in, it does what it says and is a great way to jump around the editor.

I previously came over from neovim, where there's this also great, similar plugin called [leap.nvim](https://github.com/ggandor/leap.nvim). It works almost exactly the same way, with one exception: instead of searching for just the first character after `s`, it searches for a 2-character combination. There's all sorts of other nuances for what tags are shown, based around whether that character combination is unique on the screen versus if an additional identifier character is required.

But the crux is that with a 2 character combination, you almost never run out of unique characters that you can use as tags.

Now, I'm not suggesting that this plugin should be tailored into leap.nvim but vim for me, but a customizable search pattern length (whether through an option like `g:easyjump_search_length` or a numerical prefix before the `s`, i.e. `2s` causes easyjump to expect 2 characters dynamically, if that is even possible) would be a really nice addition!

Thanks for taking the time to read this!

**Comment by girishji** [comment]
Have you tried `<tab>` or `,` or `;` when you don't see unique characters next to target? It assigns characters to new target locations, so you can jump to any location on the screen eventually.

I only keep 32 lines visible on the terminal screen on my laptop. Using s+1+1 works almost all the time without `<tab>`. If you have a large screen and more text visible, I can see this plugin having shortcomings.

**Comment by jeslinmx** [comment]
Yup, I am aware of that existing method and it works, just wished to throw out a proposal for an alternative means of achieving the same goal. 

I don't wish to impose my workflow on others, especially a freely available project I had no hand in creating, and I hope I didn't come across that way. If at another time I have some free time to take a stab at this, would you be interested in a PR for this functionality?

**Comment by girishji** [comment]
PRs are welcome, but in this case it looks trivial to implement. Give me a day or two and I will find some time to implement this. If you want to contribute, this plugin can use some tests (if you are familiar with vimscipt), but there is no obligation.

**Comment by girishji** [comment]
Please try it now. Use `2s` or set `g:easyjump_two_chars` to `true` and use `s`.

**Comment by jeslinmx** [comment]
I just saw this reply and tried it out, it works AMAZINGLY! Thank you so much!
